export const CONSTANTS = {
  REGEX: {
    SPECIAL_CHARS_WITHOUT_NEWLINE: /((?!\n)[()-\s\t])/g,
    DIGITS_AND_PLUS: /^\+?[0-9]*$/,
    ALPHABETIC_AND_LATIN_CHARS: /^[\p{Script=Latin} ]*$/u,
    NON_ALPHABETIC_AND_NON_LATIN_CHARS: /[^\p{Script=Latin}]/gu,
    POSITIVE_INTEGER: /^\d+$/,
    PO_BOX:
      /\b[P|p]?(OST|ost)?\.?\s*[O|o|0]?(ffice|FFICE)?\.?\s*[B|b][O|o|0]?[X|x]?\.?\s+[#]?(\d+)\b/,
    ANY_VALUE: /^.+$/,
    ZIP_CODE: /^[0-9]{5}(?:[- ][0-9]{4})?$/,
    INDUSTRY_CODE: /^[0-9]{6}$/,
    SSN_LAST_FOUR: /^(?!0000)[0-9]{4}$/,
    SSN_FULL_NINE: /^(?!0000)[0-9]{9}$/,
    NUMBER: /^[0-9]+$/,
    PHONE_NUMBER: /^\+?[0-9]{4,17}$/,
    CARD_NUMBER: /^[0-9]{15,16}$/,
    CARD_SECURITY_CODE: /^[0-9]{3,4}$/,
    CARD_EXPIRATION_DATE: /^(0[1-9]|1[0-2])([^0-9])?([0-9]{4}|([0-9]{2}))$/,
    ROOM_NAME: /^#[\p{Ll}0-9-]{1,100}$/u,
    ROOM_NAME_WITHOUT_LIMIT: /^#[\p{Ll}0-9-]+$/u,
    DOMAIN_BASE: "^(?:https?:\\/\\/)?(?:www\\.)?([^\\/]+)",
    ALPHANUMERIC_WITH_SPACE_AND_HYPHEN: /^[A-Za-z0-9 -]+$/,

    EMOJI:
      /[\p{Extended_Pictographic}\u200d\u{1f1e6}-\u{1f1ff}\u{1f3fb}-\u{1f3ff}\u{e0020}-\u{e007f}\u20E3\uFE0F]|[#*0-9]\uFE0F?\u20E3/gu,

    EMOJIS:
      /[\p{Extended_Pictographic}](\u200D[\p{Extended_Pictographic}]|[\u{1F3FB}-\u{1F3FF}]|[\u{E0020}-\u{E007F}]|\uFE0F|\u20E3)*|[\u{1F1E6}-\u{1F1FF}]{2}|[#*0-9]\uFE0F?\u20E3/du,

    EMOJI_SKIN_TONES: /[\u{1f3fb}-\u{1f3ff}]/gu,

    TAX_ID: /^\d{9}$/,
    NON_NUMERIC: /\D/g,
    ANY_SPACE: /\s/g,

    // Extract attachment's source from the data's html string
    ATTACHMENT_DATA: /(data-expensify-source|data-name)="([^"]+)"/g,

    EMOJI_NAME: /:[\p{L}0-9_+-]+:/gu,
    EMOJI_SUGGESTIONS: /:[\p{L}0-9_+-]{1,40}$/u,
    AFTER_FIRST_LINE_BREAK: /\n.*/g,
    LINE_BREAK: /\r\n|\r|\n|\u2028/g,
    CODE_2FA: /^\d{6}$/,
    ATTACHMENT_ID: /chat-attachments\/(\d+)/,
    HAS_COLON_ONLY_AT_THE_BEGINNING: /^:[^:]+$/,
    HAS_AT_MOST_TWO_AT_SIGNS: /^@[^@]*@?[^@]*$/,
    EMPTY_COMMENT: /^(\s)*$/,
    SPECIAL_CHAR: /[,/?"{}[\]()&^%;`$=#<>!*]/g,
    FIRST_SPACE: /.+?(?=\s)/,

    get SPECIAL_CHAR_OR_EMOJI() {
      return new RegExp(
        `[~\\n\\s]|(_\\b(?!$))|${this.SPECIAL_CHAR.source}|${this.EMOJI.source}`,
        "gu",
      );
    },

    get SPACE_OR_EMOJI() {
      return new RegExp(`(\\s+|(?:${this.EMOJI.source})+)`, "gu");
    },

    // Define the regular expression pattern to find a potential end of a mention suggestion:
    // It might be a space, a newline character, an emoji, or a special character (excluding underscores & tildes, which might be used in usernames)
    get MENTION_BREAKER() {
      return new RegExp(
        `[\\n\\s]|${this.SPECIAL_CHAR.source}|${this.EMOJI.source}`,
        "gu",
      );
    },

    get ALL_EMOJIS() {
      return new RegExp(this.EMOJIS, this.EMOJIS.flags.concat("g"));
    },

    MERGED_ACCOUNT_PREFIX: /^(MERGED_\d+@)/,
    ROUTES: {
      VALIDATE_LOGIN: /\/v($|(\/\/*))/,
      UNLINK_LOGIN: /\/u($|(\/\/*))/,
      REDUNDANT_SLASHES: /(\/{2,})|(\/$)/g,
    },
    TIME_STARTS_01: /^01:\d{2} [AP]M$/,
    TIME_FORMAT: /^\d{2}:\d{2} [AP]M$/,
    DATE_TIME_FORMAT: /^\d{2}-\d{2} \d{2}:\d{2} [AP]M$/,
    ILLEGAL_FILENAME_CHARACTERS: /\/|<|>|\*|"|:|#|\?|\\|\|/g,
    ENCODE_PERCENT_CHARACTER: /%(25)+/g,
    INVISIBLE_CHARACTERS_GROUPS: /[\p{C}\p{Z}]/gu,
    OTHER_INVISIBLE_CHARACTERS: /[\u3164]/g,
    REPORT_FIELD_TITLE: /{report:([a-zA-Z]+)}/g,
    PATH_WITHOUT_POLICY_ID: /\/w\/[a-zA-Z0-9]+(\/|$)/,
    POLICY_ID_FROM_PATH: /\/w\/([a-zA-Z0-9]+)(\/|$)/,
    SHORT_MENTION: new RegExp(
      // We are ensuring that the short mention is not inside a code block. So we check that the short mention
      // is either not preceded by an open code block or not followed by a backtick on the same line.
      `(?<!^[^\`\n]*(?:\`[^\`\n]*\`[^\`\n]*)*\`[^\`\n]*)@[\\w\\-\\+\\'#@]+(?:\\.[\\w\\-\\'\\+]+)*|@[\\w\\-\\+\\'#@]+(?:\\.[\\w\\-\\'\\+]+)*(?![^\n]*\`)`,
      "gim",
    ),
    REPORT_ID_FROM_PATH: /(?<!\/search)\/r\/(\d+)/,
    DISTANCE_MERCHANT:
      /^[0-9.]+ \w+ @ (-|-\()?[^0-9.\s]{1,3} ?[0-9.]+\)? \/ \w+$/,
    WHITESPACE: /\s+/g,
  },
  ALL_COUNTRIES: {
    AF: "Afghanistan",
    AX: "Åland Islands",
    AL: "Albania",
    DZ: "Algeria",
    AS: "American Samoa",
    AD: "Andorra",
    AO: "Angola",
    AI: "Anguilla",
    AQ: "Antarctica",
    AG: "Antigua & Barbuda",
    AR: "Argentina",
    AM: "Armenia",
    AW: "Aruba",
    AC: "Ascension Island",
    AU: "Australia",
    AT: "Austria",
    AZ: "Azerbaijan",
    BS: "Bahamas",
    BH: "Bahrain",
    BD: "Bangladesh",
    BB: "Barbados",
    BY: "Belarus",
    BE: "Belgium",
    BZ: "Belize",
    BJ: "Benin",
    BM: "Bermuda",
    BT: "Bhutan",
    BO: "Bolivia",
    BA: "Bosnia & Herzegovina",
    BW: "Botswana",
    BR: "Brazil",
    IO: "British Indian Ocean Territory",
    VG: "British Virgin Islands",
    BN: "Brunei",
    BG: "Bulgaria",
    BF: "Burkina Faso",
    BI: "Burundi",
    KH: "Cambodia",
    CM: "Cameroon",
    CA: "Canada",
    CV: "Cape Verde",
    BQ: "Caribbean Netherlands",
    KY: "Cayman Islands",
    CF: "Central African Republic",
    TD: "Chad",
    CL: "Chile",
    CN: "China",
    CX: "Christmas Island",
    CC: "Cocos (Keeling) Islands",
    CO: "Colombia",
    KM: "Comoros",
    CG: "Congo - Brazzaville",
    CD: "Congo - Kinshasa",
    CK: "Cook Islands",
    CR: "Costa Rica",
    CI: "Côte d'Ivoire",
    HR: "Croatia",
    CU: "Cuba",
    CW: "Curaçao",
    CY: "Cyprus",
    CZ: "Czech Republic",
    DK: "Denmark",
    DJ: "Djibouti",
    DM: "Dominica",
    DO: "Dominican Republic",
    EC: "Ecuador",
    EG: "Egypt",
    SV: "El Salvador",
    GQ: "Equatorial Guinea",
    ER: "Eritrea",
    EE: "Estonia",
    ET: "Ethiopia",
    FK: "Falkland Islands",
    FO: "Faroe Islands",
    FJ: "Fiji",
    FI: "Finland",
    FR: "France",
    GF: "French Guiana",
    PF: "French Polynesia",
    TF: "French Southern Territories",
    GA: "Gabon",
    GM: "Gambia",
    GE: "Georgia",
    DE: "Germany",
    GH: "Ghana",
    GI: "Gibraltar",
    GR: "Greece",
    GL: "Greenland",
    GD: "Grenada",
    GP: "Guadeloupe",
    GU: "Guam",
    GT: "Guatemala",
    GG: "Guernsey",
    GN: "Guinea",
    GW: "Guinea-Bissau",
    GY: "Guyana",
    HT: "Haiti",
    HN: "Honduras",
    HK: "Hong Kong",
    HU: "Hungary",
    IS: "Iceland",
    IN: "India",
    ID: "Indonesia",
    IR: "Iran",
    IQ: "Iraq",
    IE: "Ireland",
    IM: "Isle of Man",
    IL: "Israel",
    IT: "Italy",
    JM: "Jamaica",
    JP: "Japan",
    JE: "Jersey",
    JO: "Jordan",
    KZ: "Kazakhstan",
    KE: "Kenya",
    KI: "Kiribati",
    XK: "Kosovo",
    KW: "Kuwait",
    KG: "Kyrgyzstan",
    LA: "Laos",
    LV: "Latvia",
    LB: "Lebanon",
    LS: "Lesotho",
    LR: "Liberia",
    LY: "Libya",
    LI: "Liechtenstein",
    LT: "Lithuania",
    LU: "Luxembourg",
    MO: "Macau",
    MK: "Macedonia",
    MG: "Madagascar",
    MW: "Malawi",
    MY: "Malaysia",
    MV: "Maldives",
    ML: "Mali",
    MT: "Malta",
    MH: "Marshall Islands",
    MQ: "Martinique",
    MR: "Mauritania",
    MU: "Mauritius",
    YT: "Mayotte",
    MX: "Mexico",
    FM: "Micronesia",
    MD: "Moldova",
    MC: "Monaco",
    MN: "Mongolia",
    ME: "Montenegro",
    MS: "Montserrat",
    MA: "Morocco",
    MZ: "Mozambique",
    MM: "Myanmar (Burma)",
    NA: "Namibia",
    NR: "Nauru",
    NP: "Nepal",
    NL: "Netherlands",
    NC: "New Caledonia",
    NZ: "New Zealand",
    NI: "Nicaragua",
    NE: "Niger",
    NG: "Nigeria",
    NU: "Niue",
    NF: "Norfolk Island",
    KP: "North Korea",
    MP: "Northern Mariana Islands",
    NO: "Norway",
    OM: "Oman",
    PK: "Pakistan",
    PW: "Palau",
    PS: "Palestinian Territories",
    PA: "Panama",
    PG: "Papua New Guinea",
    PY: "Paraguay",
    PE: "Peru",
    PH: "Philippines",
    PN: "Pitcairn Islands",
    PL: "Poland",
    PT: "Portugal",
    PR: "Puerto Rico",
    QA: "Qatar",
    RE: "Réunion",
    RO: "Romania",
    RU: "Russia",
    RW: "Rwanda",
    BL: "Saint Barthélemy",
    WS: "Samoa",
    SM: "San Marino",
    ST: "São Tomé & Príncipe",
    SA: "Saudi Arabia",
    SN: "Senegal",
    RS: "Serbia",
    SC: "Seychelles",
    SL: "Sierra Leone",
    SG: "Singapore",
    SX: "Sint Maarten",
    SK: "Slovakia",
    SI: "Slovenia",
    SB: "Solomon Islands",
    SO: "Somalia",
    ZA: "South Africa",
    GS: "South Georgia & South Sandwich Islands",
    KR: "South Korea",
    SS: "South Sudan",
    ES: "Spain",
    LK: "Sri Lanka",
    SH: "St. Helena",
    KN: "St. Kitts & Nevis",
    LC: "St. Lucia",
    MF: "St. Martin",
    PM: "St. Pierre & Miquelon",
    VC: "St. Vincent & Grenadines",
    SD: "Sudan",
    SR: "Suriname",
    SJ: "Svalbard & Jan Mayen",
    SZ: "Swaziland",
    SE: "Sweden",
    CH: "Switzerland",
    SY: "Syria",
    TW: "Taiwan",
    TJ: "Tajikistan",
    TZ: "Tanzania",
    TH: "Thailand",
    TL: "Timor-Leste",
    TG: "Togo",
    TK: "Tokelau",
    TO: "Tonga",
    TT: "Trinidad & Tobago",
    TA: "Tristan da Cunha",
    TN: "Tunisia",
    TR: "Turkey",
    TM: "Turkmenistan",
    TC: "Turks & Caicos Islands",
    TV: "Tuvalu",
    UM: "U.S. Outlying Islands",
    VI: "U.S. Virgin Islands",
    UG: "Uganda",
    UA: "Ukraine",
    AE: "United Arab Emirates",
    GB: "United Kingdom",
    US: "United States",
    UY: "Uruguay",
    UZ: "Uzbekistan",
    VU: "Vanuatu",
    VA: "Vatican City",
    VE: "Venezuela",
    VN: "Vietnam",
    WF: "Wallis & Futuna",
    EH: "Western Sahara",
    YE: "Yemen",
    ZM: "Zambia",
    ZW: "Zimbabwe",
  },
};
